date-fullyear = 4DIGIT
date-mday = 2DIGIT
date-month = 2DIGIT
date-time = full-date "T" full-time
full-date = date-fullyear "-" date-month "-" date-mday
full-time = partial-time time-offset
partial-time = time-hour ":" time-minute ":" time-second [time-secfrac]
time-hour = 2DIGIT
time-minute = 2DIGIT
time-numoffset = ("+" / "-") time-hour ":" time-minute
time-offset = "Z" / time-numoffset
time-secfrac = "." 1*DIGIT
time-second = 2DIGIT