authority = [userinfo "@"] host [":" rfc3986-PORT]
dec-octet = DIGIT / %x31-39 DIGIT / "1" 2DIGIT / "2" %x30-34 DIGIT / "25" %x30-35
fragment = *(pchar / "/" / "?")
h16 = 1*4HEXDIG
hier-part = "//" authority path-abempty / path-absolute / path-rootless / path-empty
host = IP-literal / IPv4address / reg-name
IP-literal = "[" (IPv6address / IPvFuture) "]"
IPv4address = dec-octet "." dec-octet "." dec-octet "." dec-octet
IPv6address = 6(h16 ":") ls32 / "::" 5(h16 ":") ls32 / [h16] "::" 4(h16 ":") ls32 / [[(h16 ":")] h16] "::" 3(h16 ":") ls32 / [*2(h16 ":") h16] "::" 2(h16 ":") ls32 / [*3(h16 ":") h16] "::" h16 ":" ls32 / [*4(h16 ":") h16] "::" ls32 / [*5(h16 ":") h16] "::" h16 / [*6(h16 ":") h16] "::"
IPvFuture = "v" 1*HEXDIG "." 1*(unreserved / sub-delims / ":")
ls32 = (h16 ":" h16) / IPv4address
path-abempty = *("/" segment)
path-absolute = "/" [segment-nz *("/" segment)]
path-empty = 0<pchar>
path-noscheme = segment-nz-nc *("/" segment)
path-rootless = segment-nz *("/" segment)
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
pct-encoded = "%" HEXDIG HEXDIG
query = *(pchar / "/" / "?")
reg-name = *(unreserved / pct-encoded / sub-delims)
relative-part = "//" authority path-abempty / path-absolute / path-noscheme / path-empty
relative-ref = relative-part ["?" query] ["#" fragment]
scheme = ALPHA *(ALPHA / DIGIT / "+" / "-" / ".")
segment = *pchar
segment-nz = 1*pchar
segment-nz-nc = 1*(unreserved / pct-encoded / sub-delims / "@")
sub-delims = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
URI-reference = rfc3986-URI / relative-ref
userinfo = *(unreserved / pct-encoded / sub-delims / ":")
addr-spec = local-part "@" domain
atext = ALPHA / DIGIT / "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "/" / "=" / "?" / "^" / "_" / "`" / "{" / "|" / "}" / "~"
atom = [CFWS] 1*atext [CFWS]
ccontent = ctext / quoted-pair / comment
CFWS = *([FWS] comment) (([FWS] comment) / FWS)
comment = "(" *([FWS] ccontent) [FWS] ")"
ctext = NO-WS-CTL / %d33-39 / %d42-91 / %d93-126
dcontent = dtext / quoted-pair
domain = dot-atom / domain-literal / obs-domain
domain-literal = [CFWS] "[" *([FWS] dcontent) [FWS] "]" [CFWS]
dot-atom = [CFWS] dot-atom-text [CFWS]
dot-atom-text = 1*atext *("." 1*atext)
dtext = NO-WS-CTL / %d33-90 / %d94-126
FWS = ([*WSP CRLF] 1*WSP) / obs-FWS
local-part = dot-atom / quoted-string / obs-local-part
NO-WS-CTL = %d1-8 / %d11 / %d12 / %d14-31 / %d127
obs-char = %d0-9 / %d11 / %d12 / %d14-127
obs-domain = atom *("." atom)
obs-FWS = 1*WSP *(CRLF 1*WSP)
obs-local-part = word *("." word)
obs-qp = "\" (%d0-127)
obs-text = *LF *CR *(obs-char *LF *CR)
qcontent = qtext / quoted-pair
qtext = NO-WS-CTL / %d33 / %d35-91 / %d93-126
quoted-pair = ("\" rfc2822-TEXT) / obs-qp
quoted-string = [CFWS] DQUOTE *([FWS] qcontent) [FWS] DQUOTE [CFWS]
word = atom / quoted-string
rfc3986-PORT = *DIGIT
rfc3986-URI = scheme ":" hier-part ["?" query] ["#" fragment]
rfc2822-TEXT = %d1-9 / %d11 / %d12 / %d14-127 / obs-text
address-and-comment = addr-spec 1*SP "(" 1*email-safe ")"
addrtype = token
alpha-numeric = ALPHA / DIGIT
att-field = token
att-value = byte-string
attribute = (att-field ":" att-value) / att-field
attribute-fields = *(%d97 "=" attribute CRLF)
b1 = decimal-uchar
bandwidth = 1*DIGIT
bandwidth-fields = *(%d98 "=" bwtype ":" bandwidth CRLF)
base64 = *base64-unit [base64-pad]
base64-char = ALPHA / DIGIT / "+" / "/"
base64-pad = 2base64-char "==" / 3base64-char "="
base64-unit = 4base64-char
bwtype = token
byte-string = 1*(%x1-9 / %xb-c / %xe-ff)
connection-address = multicast-address / unicast-address
connection-field = [%d99 "=" nettype SP addrtype SP connection-address CRLF]
decimal-uchar = DIGIT / POS-DIGIT DIGIT / ("1" 2*(DIGIT)) / ("2" ("0" / "1" / "2" / "3" / "4") DIGIT) / ("2" "5" ("0" / "1" / "2" / "3" / "4" / "5"))
dispname-and-address = 1*email-safe 1*SP "<" addr-spec ">"
email-address = address-and-comment / dispname-and-address / addr-spec
email-fields = *(%d101 "=" email-address CRLF)
email-safe = %x1-9 / %xb-c / %xe-27 / %x2a-3b / %d61 / %x3f-ff
extn-addr = non-ws-string
fixed-len-time-unit = %d100 / %d104 / %d109 / %d115
fmt = token
FQDN = 4*(alpha-numeric / "-" / ".")
hex4 = 1*4HEXDIG
hexpart = hexseq / hexseq "::" [hexseq] / "::" [hexseq]
hexseq = hex4 *(":" hex4)
information-field = [%d105 "=" text CRLF]
integer = POS-DIGIT *DIGIT
IP4-address = b1 3("." decimal-uchar)
IP4-multicast = m1 3("." decimal-uchar) "/" ttl ["/" integer]
IP6-address = hexpart [":" IP4-address]
IP6-multicast = hexpart ["/" integer]
key-field = [%d107 "=" key-type CRLF]
key-type = %d112 %d114 %d111 %d109 %d112 %d116 / %d99 %d108 %d101 %d97 %d114 ":" text / %d98 %d97 %d115 %d101 "64:" base64 / %d117 %d114 %d105 ":" uri
m1 = ("22" ("4" / "5" / "6" / "7" / "8" / "9")) / ("23" DIGIT)
media = token
media-descriptions = *(media-field information-field *connection-field bandwidth-fields key-field attribute-fields)
media-field = %d109 "=" media SP port ["/" integer] SP proto 1*(SP fmt) CRLF
multicast-address = IP4-multicast / IP6-multicast / FQDN / extn-addr
nettype = token
non-ws-string = 1*(VCHAR / %x80-ff)
origin-field = %d111 "=" username SP sess-id SP sess-version SP nettype SP addrtype SP unicast-address CRLF
phone = ["+"] DIGIT 1*(SP / "-" / DIGIT)
phone-fields = *(%d112 "=" phone-number CRLF)
phone-number = phone *SP "(" 1*email-safe ")" / 1*email-safe "<" phone ">" / phone
port = 1*DIGIT
POS-DIGIT = %x31-39
proto = token *("/" token)
proto-version = %d118 "=" 1*DIGIT CRLF
repeat-fields = %d114 "=" repeat-interval SP typed-time 1*(SP typed-time)
repeat-interval = POS-DIGIT *DIGIT [fixed-len-time-unit]
sess-id = 1*DIGIT
sess-version = 1*DIGIT
session-description = proto-version origin-field session-name-field information-field uri-field email-fields phone-fields connection-field bandwidth-fields time-fields key-field attribute-fields media-descriptions
session-name-field = %d115 "=" text CRLF
start-time = time / "0"
stop-time = time / "0"
text = byte-string
time = POS-DIGIT 9*DIGIT
time-fields = 1*(%d116 "=" start-time SP stop-time *(CRLF repeat-fields) CRLF) [zone-adjustments CRLF]
token = 1*(token-char)
token-char = %d33 / %x23-27 / %x2a-2b / %x2d-2e / %x30-39 / %x41-5a / %x5e-7e
ttl = (POS-DIGIT *2DIGIT) / "0"
typed-time = 1*DIGIT [fixed-len-time-unit]
unicast-address = IP4-address / IP6-address / FQDN / extn-addr
uri = URI-reference
uri-field = [%d117 "=" uri CRLF]
username = non-ws-string
zone-adjustments = %d122 "=" time SP ["-"] typed-time *(SP time SP ["-"] typed-time)