fields = *(trace *optional-field / *(resent-date / resent-from / resent-sender / resent-to / resent-cc / resent-bcc / resent-msg-id)) *(orig-date / from / sender / reply-to / to / cc / bcc / message-id / in-reply-to / references / subject / comments / keywords / optional-field)
trace = [return] 1*received
optional-field = field-name ":" unstructured CRLF
resent-date = "Resent-Date:" date-time CRLF
resent-from = "Resent-From:" mailbox-list CRLF
resent-sender = "Resent-Sender:" mailbox CRLF
resent-to = "Resent-To:" address-list CRLF
resent-cc = "Resent-Cc:" address-list CRLF
resent-bcc = "Resent-Bcc:" [address-list / CFWS] CRLF
resent-msg-id = "Resent-Message-ID:" msg-id CRLF
orig-date = "Date:" date-time CRLF
from = "From:" mailbox-list CRLF
sender = "Sender:" mailbox CRLF
reply-to = "Reply-To:" address-list CRLF
to = "To:" address-list CRLF
cc = "Cc:" address-list CRLF
bcc = "Bcc:" [address-list / CFWS] CRLF
message-id = "Message-ID:" msg-id CRLF
in-reply-to = "In-Reply-To:" 1*msg-id CRLF
references = "References:" 1*msg-id CRLF
subject = "Subject:" unstructured CRLF
comments = "Comments:" unstructured CRLF
keywords = "Keywords:" phrase *("," phrase) CRLF
return = "Return-Path:" path CRLF
received = "Received:" *received-token ";" date-time CRLF
field-name = 1*ftext
unstructured = (*([FWS] VCHAR) *WSP) / obs-unstruct
date-time = [day-of-week ","] date time [CFWS]
mailbox-list = (mailbox *("," mailbox)) / obs-mbox-list
mailbox = name-addr / addr-spec
address-list = (address *("," address)) / obs-addr-list
CFWS = (1*([FWS] comment) [FWS]) / FWS
msg-id = [CFWS] "<" id-left "@" id-right ">" [CFWS]
phrase = 1*word / obs-phrase
path = angle-addr / ([CFWS] "<" [CFWS] ">" [CFWS])
received-token = word / angle-addr / addr-spec / domain
ftext = %d33-57 / %d59-126
FWS = ([*WSP CRLF] 1*WSP) / obs-FWS
obs-unstruct = *((*LF *CR *(obs-utext *LF *CR)) / FWS)
day-of-week = ([FWS] day-name) / obs-day-of-week
date = day month year
time = time-of-day zone
obs-mbox-list = *([CFWS] ",") mailbox *("," [mailbox / CFWS])
name-addr = [display-name] angle-addr
addr-spec = local-part "@" domain
address = mailbox / group
obs-addr-list = *([CFWS] ",") address *("," [address / CFWS])
comment = "(" *([FWS] ccontent) [FWS] ")"
id-left = dot-atom-text / obs-id-left
id-right = dot-atom-text / no-fold-literal / obs-id-right
word = atom / quoted-string
obs-phrase = word *(word / "." / CFWS)
angle-addr = [CFWS] "<" addr-spec ">" [CFWS] / obs-angle-addr
domain = dot-atom / domain-literal / obs-domain
obs-FWS = 1*WSP *(CRLF 1*WSP)
obs-utext = %d0 / obs-NO-WS-CTL / VCHAR
day-name = "Mon" / "Tue" / "Wed" / "Thu" / "Fri" / "Sat" / "Sun"
obs-day-of-week = [CFWS] day-name [CFWS]
day = ([FWS] 1*2DIGIT FWS) / obs-day
month = "Jan" / "Feb" / "Mar" / "Apr" / "May" / "Jun" / "Jul" / "Aug" / "Sep" / "Oct" / "Nov" / "Dec"
year = (FWS 4*DIGIT FWS) / obs-year
time-of-day = hour ":" minute [":" second]
zone = (FWS ("+" / "-") 4DIGIT) / obs-zone
display-name = phrase
local-part = dot-atom / quoted-string / obs-local-part
group = display-name ":" [group-list] ";" [CFWS]
ccontent = ctext / quoted-pair / comment
dot-atom-text = 1*atext *("." 1*atext)
obs-id-left = local-part
no-fold-literal = "[" *dtext "]"
obs-id-right = domain
atom = [CFWS] 1*atext [CFWS]
quoted-string = [CFWS] DQUOTE *([FWS] qcontent) [FWS] DQUOTE [CFWS]
obs-angle-addr = [CFWS] "<" obs-route addr-spec ">" [CFWS]
dot-atom = [CFWS] dot-atom-text [CFWS]
domain-literal = [CFWS] "[" *([FWS] dtext) [FWS] "]" [CFWS]
obs-domain = atom *("." atom)
obs-NO-WS-CTL = %d1-8 / %d11 / %d12 / %d14-31 / %d127
obs-day = [CFWS] 1*2DIGIT [CFWS]
obs-year = [CFWS] 2*DIGIT [CFWS]
hour = 2DIGIT / obs-hour
minute = 2DIGIT / obs-minute
second = 2DIGIT / obs-second
obs-zone = "UT" / "GMT" / "EST" / "EDT" / "CST" / "CDT" / "MST" / "MDT" / "PST" / "PDT" / %d65-73 / %d75-90 / %d97-105 / %d107-122
obs-local-part = word *("." word)
group-list = mailbox-list / CFWS / obs-group-list
ctext = %d33-39 / %d42-91 / %d93-126 / obs-ctext
quoted-pair = ("\" (VCHAR / WSP)) / obs-qp
atext = ALPHA / DIGIT / "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "/" / "=" / "?" / "^" / "_" / "`" / "{" / "|" / "}" / "~"
dtext = %d33-90 / %d94-126 / obs-dtext
qcontent = qtext / quoted-pair
obs-route = obs-domain-list ":"
obs-hour = [CFWS] 2DIGIT [CFWS]
obs-minute = [CFWS] 2DIGIT [CFWS]
obs-second = [CFWS] 2DIGIT [CFWS]
obs-group-list = 1*([CFWS] ",") [CFWS]
obs-ctext = obs-NO-WS-CTL
obs-qp = "\" (%d0 / obs-NO-WS-CTL / LF / CR)
obs-dtext = obs-NO-WS-CTL / quoted-pair
qtext = %d33 / %d35-91 / %d93-126 / obs-qtext
obs-domain-list = *(CFWS / ",") "@" domain *("," [CFWS] ["@" domain])
obs-qtext = obs-NO-WS-CTL
; Extracted from IETF RFC 9477
; Copyright (c) IETF Trust and the persons identified as authors of the code. All rights reserved.
; Redistribution and use in source and binary forms, with or without modification, is permitted pursuant to, and subject to the license terms contained in, the Revised BSD License set forth in Section 4.c of the IETF Trust's Legal Provisions Relating to IETF Documents (https://trustee.ietf.org/license-info).

fields =/ cfbl-address

cfbl-address = "CFBL-Address:" CFWS addr-spec
               [";" CFWS report-format] CRLF

report-format = %s"report=" (%s"arf" / %s"xarf")


fields =/ cfbl-feedback-id

cfbl-feedback-id = "CFBL-Feedback-ID:" CFWS fid CRLF

fid = 1*(atext / ":" / CFWS)
