robotstxt = *(group / emptyline)
group = startgroupline *(startgroupline / emptyline) *(rule / emptyline)
startgroupline = *WS "user-agent" *WS ":" *WS product-token EOL
rule = *WS ("allow" / "disallow") *WS ":" *WS (path-pattern / empty-pattern) EOL
product-token = identifier / "*"
path-pattern = "/" *UTF8-char-noctl
empty-pattern = *WS
identifier = 1*(%d45 / %x41-5a / %d95 / %x61-7a)
comment = "#" *(UTF8-char-noctl / WS / "#")
emptyline = EOL
EOL = *WS [comment] NL
NL = %d13 / %d10 / %xd
WS = %d32 / %d9
UTF8-char-noctl = UTF8-1-noctl / UTF8-2 / UTF8-3 / UTF8-4
UTF8-1-noctl = %d33 / %d34 / %x24-7f
UTF8-2 = %xc2-df UTF8-tail
UTF8-3 = %d195 %xa0-bf UTF8-tail / %xe1-ec 2UTF8-tail / %d195 %x80-9f UTF8-tail / %xee-ef 2UTF8-tail
UTF8-4 = %d195 %x90-bf 2UTF8-tail / %xf1-f3 3UTF8-tail / %d195 %x80-8f 2UTF8-tail
UTF8-tail = %x80-bf