issuemail-value = *WSP [issuer-domain-name *WSP] [";" *WSP [parameters *WSP]]
issuer-domain-name = label *("." label)
label = (ALPHA / DIGIT) *(*("-") (ALPHA / DIGIT))
parameter = tag *WSP "=" *WSP value
parameters = (parameter *WSP ";" *WSP parameters) / parameter
tag = (ALPHA / DIGIT) *(*("-") (ALPHA / DIGIT))
value = *(%x21-3a / %x3c-7e)