alpha-lc = %x61-7a
alpn-id = 1*255OCTET
char-string = contiguous / quoted
comma-separated = [escaped-item *("," escaped-item)]
contiguous = 1*(non-special / escaped)
dec-octet = ("0" / "1") 2DIGIT / "2" ((%x30-34 DIGIT) / ("5" %x30-35))
escaped = "\" (non-digit / dec-octet)
escaped-item = 1*(item-allowed / "\," / "\\")
item = 1*OCTET
item-allowed = %x0-2b / %x2d-5b / %x5d-ff
non-digit = %x21-2f / %x3a-7e
non-special = %d33 / %x23-27 / %x2a-3a / %x3c-5b / %x5d-7e
quoted = DQUOTE *(contiguous / (["\"] WSP)) DQUOTE
simple-comma-separated = [simple-item *("," simple-item)]
simple-item = 1*item-allowed
SvcParam = SvcParamKey ["=" SvcParamValue]
SvcParamKey = 1*63(alpha-lc / DIGIT / "-")
SvcParamValue = char-string
value = *OCTET