addr-spec = local-part "@" domain
address = mailbox / group
address-list = (address *("," address)) / obs-addr-list
angle-addr = [CFWS] "<" addr-spec ">" [CFWS] / obs-angle-addr
atext = ALPHA / DIGIT / "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "/" / "=" / "?" / "^" / "_" / "`" / "{" / "|" / "}" / "~"
atom = [CFWS] 1*atext [CFWS]
bcc = "Bcc:" [address-list / CFWS] CRLF
cc = "Cc:" address-list CRLF
ccontent = ctext / quoted-pair / comment
CFWS = (1*([FWS] comment) [FWS]) / FWS
comment = "(" *([FWS] ccontent) [FWS] ")"
comments = "Comments:" unstructured CRLF
ctext = %d33-39 / %d42-91 / %d93-126 / obs-ctext
date = day month year
date-time = [day-of-week ","] date time [CFWS]
day = ([FWS] 1*2DIGIT FWS) / obs-day
day-name = "Mon" / "Tue" / "Wed" / "Thu" / "Fri" / "Sat" / "Sun"
day-of-week = ([FWS] day-name) / obs-day-of-week
display-name = phrase
domain = dot-atom / domain-literal / obs-domain
domain-literal = [CFWS] "[" *([FWS] dtext) [FWS] "]" [CFWS]
dot-atom = [CFWS] dot-atom-text [CFWS]
dot-atom-text = 1*atext *("." 1*atext)
dtext = %d33-90 / %d94-126 / obs-dtext
field-name = 1*ftext
fields = *(trace *optional-field / *(resent-date / resent-from / resent-sender / resent-to / resent-cc / resent-bcc / resent-msg-id)) *(orig-date / from / sender / reply-to / to / cc / bcc / message-id / in-reply-to / references / subject / comments / keywords / optional-field) / cfbl-address / cfbl-feedback-id
from = "From:" mailbox-list CRLF
ftext = %d33-57 / %d59-126
FWS = ([*WSP CRLF] 1*WSP) / obs-FWS
group = display-name ":" [group-list] ";" [CFWS]
group-list = mailbox-list / CFWS / obs-group-list
hour = 2DIGIT / obs-hour
id-left = dot-atom-text / obs-id-left
id-right = dot-atom-text / no-fold-literal / obs-id-right
in-reply-to = "In-Reply-To:" 1*msg-id CRLF
keywords = "Keywords:" phrase *("," phrase) CRLF
local-part = dot-atom / quoted-string / obs-local-part
mailbox = name-addr / addr-spec
mailbox-list = (mailbox *("," mailbox)) / obs-mbox-list
message-id = "Message-ID:" msg-id CRLF
minute = 2DIGIT / obs-minute
month = "Jan" / "Feb" / "Mar" / "Apr" / "May" / "Jun" / "Jul" / "Aug" / "Sep" / "Oct" / "Nov" / "Dec"
msg-id = [CFWS] "<" id-left "@" id-right ">" [CFWS]
name-addr = [display-name] angle-addr
no-fold-literal = "[" *dtext "]"
obs-addr-list = *([CFWS] ",") address *("," [address / CFWS])
obs-angle-addr = [CFWS] "<" obs-route addr-spec ">" [CFWS]
obs-ctext = obs-NO-WS-CTL
obs-day = [CFWS] 1*2DIGIT [CFWS]
obs-day-of-week = [CFWS] day-name [CFWS]
obs-domain = atom *("." atom)
obs-domain-list = *(CFWS / ",") "@" domain *("," [CFWS] ["@" domain])
obs-dtext = obs-NO-WS-CTL / quoted-pair
obs-FWS = 1*WSP *(CRLF 1*WSP)
obs-group-list = 1*([CFWS] ",") [CFWS]
obs-hour = [CFWS] 2DIGIT [CFWS]
obs-id-left = local-part
obs-id-right = domain
obs-local-part = word *("." word)
obs-mbox-list = *([CFWS] ",") mailbox *("," [mailbox / CFWS])
obs-minute = [CFWS] 2DIGIT [CFWS]
obs-NO-WS-CTL = %d1-8 / %d11 / %d12 / %d14-31 / %d127
obs-phrase = word *(word / "." / CFWS)
obs-qp = "\" (%d0 / obs-NO-WS-CTL / LF / CR)
obs-qtext = obs-NO-WS-CTL
obs-route = obs-domain-list ":"
obs-second = [CFWS] 2DIGIT [CFWS]
obs-unstruct = *((*LF *CR *(obs-utext *LF *CR)) / FWS)
obs-utext = %d0 / obs-NO-WS-CTL / VCHAR
obs-year = [CFWS] 2*DIGIT [CFWS]
obs-zone = "UT" / "GMT" / "EST" / "EDT" / "CST" / "CDT" / "MST" / "MDT" / "PST" / "PDT" / %d65-73 / %d75-90 / %d97-105 / %d107-122
optional-field = field-name ":" unstructured CRLF
orig-date = "Date:" date-time CRLF
path = angle-addr / ([CFWS] "<" [CFWS] ">" [CFWS])
phrase = 1*word / obs-phrase
qcontent = qtext / quoted-pair
qtext = %d33 / %d35-91 / %d93-126 / obs-qtext
quoted-pair = ("\" (VCHAR / WSP)) / obs-qp
quoted-string = [CFWS] DQUOTE *([FWS] qcontent) [FWS] DQUOTE [CFWS]
received = "Received:" *received-token ";" date-time CRLF
received-token = word / angle-addr / addr-spec / domain
references = "References:" 1*msg-id CRLF
reply-to = "Reply-To:" address-list CRLF
resent-bcc = "Resent-Bcc:" [address-list / CFWS] CRLF
resent-cc = "Resent-Cc:" address-list CRLF
resent-date = "Resent-Date:" date-time CRLF
resent-from = "Resent-From:" mailbox-list CRLF
resent-msg-id = "Resent-Message-ID:" msg-id CRLF
resent-sender = "Resent-Sender:" mailbox CRLF
resent-to = "Resent-To:" address-list CRLF
return = "Return-Path:" path CRLF
second = 2DIGIT / obs-second
sender = "Sender:" mailbox CRLF
subject = "Subject:" unstructured CRLF
time = time-of-day zone
time-of-day = hour ":" minute [":" second]
to = "To:" address-list CRLF
trace = [return] 1*received
unstructured = (*([FWS] VCHAR) *WSP) / obs-unstruct
word = atom / quoted-string
year = (FWS 4*DIGIT FWS) / obs-year
zone = (FWS ("+" / "-") 4DIGIT) / obs-zone
cfbl-address = "CFBL-Address:" CFWS addr-spec [";" CFWS report-format] CRLF
cfbl-feedback-id = "CFBL-Feedback-ID:" CFWS fid CRLF
fid = 1*(atext / ":" / CFWS)
report-format = "report=" ("arf" / "xarf")